#!/rascal/raspdf/pyinst/bin/python

import sys
import os, os.path 

#If this is a softlink to somewhere else we need the destination path
rd = __file__
while os.path.islink(rd): rd = os.path.abspath(os.readlink(rd))
rd = os.path.dirname(rd)
sys.path.append(os.path.join(rd,'lib'))

import raspdf
raspdf.main()
