#!/rascal/raspdf_testing/PYTHONINSTALL/bin/python
import sys
import os, os.path 

#If this is a softlink to somewhere else we need the destination path
rd = __file__
while os.path.islink(rd): rd = os.readlink(rd)
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(rd)),'lib'))

import raspdf
raspdf.main()
